A good resource for learning and practicing about pandas and numpy

[Python for Data Analysis_ Data Wrangling with pandas, NumPy, and Jupyter (2022, O'Reilly Media)](https://drive.google.com/file/d/1GA3KRXSIXI9p5DCU-ADDnxkWuL1ZeXNK/view?usp=sharing)

-----------

## sqlite3

Connection

In [ ]:
import sqlite3
con = sqlite3.connect("tutorial.db")

make an object to have a connection to database

In [ ]:
cur = con.cursor()

write a simple quary and execute it

In [ ]:
cur.execute("CREATE TABLE movie(title, year, score)")

fetch all the executed rocords from quaries

In [ ]:
res = cur.execute("SELECT name FROM sqlite_master")
res.fetchone()

In [ ]:
res = cur.execute("SELECT name FROM sqlite_master WHERE name='spam'")
res.fetchone() is None

insert rows to table

In [ ]:
cur.execute("""
    INSERT INTO movie VALUES
        ('Monty Python and the Holy Grail', 1975, 8.2),
        ('And Now for Something Completely Different', 1971, 7.5)
""")

use commit method to finalize what we have sent to database by executing our quaries

In [ ]:
con.commit()

execute multiple quaries by executemany method

In [ ]:
data = [
    ("Monty Python Live at the Hollywood Bowl", 1982, 7.9),
    ("Monty Python's The Meaning of Life", 1983, 7.5),
    ("Monty Python's Life of Brian", 1979, 8.0),
]
cur.executemany("INSERT INTO movie VALUES(?, ?, ?)", data)
con.commit()

In [ ]:
for row in cur.execute("SELECT year, title FROM movie ORDER BY year"):
    print(row)

close connection we made before and create a new connection

In [ ]:
con.close()
new_con = sqlite3.connect("tutorial.db")
new_cur = new_con.cursor()
res = new_cur.execute("SELECT title, year FROM movie ORDER BY score DESC")
title, year = res.fetchone()
print(f'The highest scoring Monty Python movie is {title!r}, released in {year}')

----

In [ ]:
%pip install sklearn

# Imputer
1. Simple Imputer

2. KNN

3. Iterative Imputer(Regression)


## Simple Imputer

Replace missing values using a descriptive statistic (e.g. mean, median, or most frequent) along each column, or using a constant value.

In [4]:
import numpy as np
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
train = [[7, 2, 3], [4, np.nan, 6], [10, 5, 9]]

imputer.fit(train)

SimpleImputer()

In [5]:
X = [[np.nan, 2, 3], [4, np.nan, 6], [10, np.nan, 9]]
print(imputer.transform(X))

[[ 7.   2.   3. ]
 [ 4.   3.5  6. ]
 [10.   3.5  9. ]]


## KNN

Each sample’s missing values are imputed using the mean value from n_neighbors nearest neighbors found in the training set. Two samples are close if the features that neither is missing are close.

In [10]:
import numpy as np
from sklearn.impute import KNNImputer


X = [[1, 2, np.nan], [3, 4, 3], [np.nan, 6, 5], [8, 8, 7]]
imputer = KNNImputer(n_neighbors=2)

In [9]:
imputer.fit_transform(X)

array([[1., 2., 5.],
       [3., 4., 3.],
       [4., 6., 5.],
       [8., 8., 7.]])

## Iterative Imputer

Multivariate imputer that estimates each feature from all the others.

A strategy for imputing missing values by modeling each feature with missing values as a function of other features in a round-robin fashion.

In [11]:
import numpy as np
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

imputer = IterativeImputer(random_state=0)

imputer.fit([[7, 2, 3], [4, np.nan, 6], [10, 5, 9]])

IterativeImputer(random_state=0)

X = [[np.nan, 2, 3], [4, np.nan, 6], [10, np.nan, 9]]

imputer.transform(X)

array([[ 6.95847623,  2.        ,  3.        ],
       [ 4.        ,  2.6000004 ,  6.        ],
       [10.        ,  4.99999933,  9.        ]])

# Outlier Detection

## Isolation Forest

The IsolationForest ‘isolates’ observations by randomly selecting a feature and then randomly selecting a split value between the maximum and minimum values of the selected feature.

In [13]:
from sklearn.ensemble import IsolationForest


X = [[-1.1], [0.3], [0.5], [100]]
clf = IsolationForest(random_state=0).fit(X)
clf.predict([[0.1], [0], [90]])

array([ 1,  1, -1])

## EllipticEnvelope

An object for detecting outliers in a Gaussian distributed dataset.

In [14]:
import numpy as np
from sklearn.covariance import EllipticEnvelope

true_cov = np.array([[.8, .3],
                      [.3, .4]])
X = np.random.RandomState(0).multivariate_normal(mean=[0, 0],
                                                  cov=true_cov,
                                                  size=500)

cov = EllipticEnvelope(random_state=0).fit(X)

# predict returns 1 for an inlier and -1 for an outlier
cov.predict([[0, 0],
              [3, 3]])

array([ 1, -1])

## OneClassSVM

Unsupervised Outlier Detection.

Estimate the support of a high-dimensional distribution.

The implementation is based on libsvm.

In [15]:
from sklearn.svm import OneClassSVM

X = [[0], [0.44], [0.45], [0.46], [1]]
clf = OneClassSVM(gamma='auto').fit(X)
clf.predict(X)

array([-1,  1,  1,  1, -1], dtype=int64)

## LocalOutlierFactor

Unsupervised Outlier Detection using the Local Outlier Factor (LOF).

The anomaly score of each sample is called the Local Outlier Factor. It measures the local deviation of the density of a given sample with respect to its neighbors. It is local in that the anomaly score depends on how isolated the object is with respect to the surrounding neighborhood. More precisely, locality is given by k-nearest neighbors, whose distance is used to estimate the local density. By comparing the local density of a sample to the local densities of its neighbors, one can identify samples that have a substantially lower density than their neighbors. These are considered outliers.

In [17]:
import numpy as np
from sklearn.neighbors import LocalOutlierFactor

X = [[-1.1], [0.2], [101.1], [0.3]]
clf = LocalOutlierFactor(n_neighbors=2)
clf.fit_predict(X)

array([ 1,  1, -1,  1])

# Order Encoding

## LabelEncoder

Encode target labels with value between 0 and n_classes-1.

This transformer should be used to encode target values, i.e. y, and not the input X.

In [20]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
le.fit([1, 2, 2, 6])
le.transform([1, 1, 2, 6])

array([0, 0, 1, 2], dtype=int64)

In [21]:
le.inverse_transform([0, 0, 1, 2])

array([1, 1, 2, 6])

In [23]:
le = LabelEncoder()
le.fit(["paris", "paris", "tokyo", "amsterdam"])
list(le.classes_)

['amsterdam', 'paris', 'tokyo']

In [24]:
le.transform(["tokyo", "tokyo", "paris"])

array([2, 2, 1])

In [25]:
list(le.inverse_transform([2, 2, 1]))

['tokyo', 'tokyo', 'paris']

## OneHotEncoder

Encode categorical features as a one-hot numeric array.

The input to this transformer should be an array-like of integers or strings, denoting the values taken on by categorical (discrete) features. The features are encoded using a one-hot (aka ‘one-of-K’ or ‘dummy’) encoding scheme. This creates a binary column for each category and returns a sparse matrix or dense array (depending on the sparse_output parameter)

In [30]:
from sklearn.preprocessing import OneHotEncoder

enc = OneHotEncoder(handle_unknown='ignore')
X = [['Male', 1], ['Female', 3], ['Female', 2]]
enc.fit(X)
enc.categories_

[array(['Female', 'Male'], dtype=object), array([1, 2, 3], dtype=object)]

In [34]:
enc.transform([['Female', 1], ['Male', 2]]).toarray()

array([[1., 0., 1., 0., 0.],
       [0., 1., 0., 1., 0.]])

In [36]:
enc.inverse_transform([[1, 0, 1, 0, 0], [0, 1, 0, 1, 0]])

array([['Female', 1],
       ['Male', 2]], dtype=object)

In [37]:
enc.get_feature_names_out(['gender', 'group'])

array(['gender_Female', 'gender_Male', 'group_1', 'group_2', 'group_3'],
      dtype=object)

## OrdinalEncoder

Encode categorical features as an integer array.

The input to this transformer should be an array-like of integers or strings, denoting the values taken on by categorical (discrete) features. The features are converted to ordinal integers. This results in a single column of integers (0 to n_categories - 1) per feature.

In [38]:
from sklearn.preprocessing import OrdinalEncoder
enc = OrdinalEncoder()
X = [['Male', 1], ['Female', 3], ['Female', 2]]
enc.fit(X)

OrdinalEncoder()

In [40]:
enc.transform([['Female', 3], ['Male', 1]])

array([[0., 2.],
       [1., 0.]])

In [42]:
enc.inverse_transform([[0, 2], [1, 0]])

array([['Female', 3],
       ['Male', 1]], dtype=object)

## ColumnTransformer

Applies transformers to columns of an array or pandas DataFrame.

This estimator allows different columns or column subsets of the input to be transformed separately and the features generated by each transformer will be concatenated to form a single feature space. This is useful for heterogeneous or columnar data, to combine several feature extraction mechanisms or transformations into a single transformer.

In [43]:
import numpy as np
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import Normalizer

ct = ColumnTransformer(
    [("norm1", Normalizer(norm='l1'), [0, 1]),
     ("norm2", Normalizer(norm='l1'), slice(2, 4))])

X = np.array([[0., 1., 2., 2.],
              [1., 1., 0., 1.]])

# Normalizer scales each row of X to unit norm. A separate scaling
# is applied for the two first and two last elements of each
# row independently.
ct.fit_transform(X)

array([[0. , 1. , 0.5, 0.5],
       [0.5, 0.5, 0. , 1. ]])

# Scalers

1. Min - Max
2. Standard (Much less effected by outliers)

## MinMaxScaler

Transform features by scaling each feature to a given range.

This estimator scales and translates each feature individually such that it is in the given range on the training set, e.g. between zero and one.

X_std = (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))
X_scaled = X_std * (max - min) + min

MinMaxScaler doesn’t reduce the effect of outliers, but it linearily scales them down into a fixed range, where the largest occuring data point corresponds to the maximum value and the smallest one corresponds to the minimum value.

In [49]:
from sklearn.preprocessing import MinMaxScaler
data = [[-1, 2], [-0.5, 6], [0, 10], [1, 18]]
scaler = MinMaxScaler()
scaler.fit(data)

MinMaxScaler()

In [50]:
scaler.data_max_

array([ 1., 18.])

In [51]:
scaler.transform(data)

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [52]:
scaler.transform([[2, 2]])

array([[1.5, 0. ]])

## Standardize

Standardize features by removing the mean and scaling to unit variance.

The standard score of a sample x is calculated as:

    z = (x - u) / s

StandardScaler is sensitive to outliers, and the features may scale differently from each other in the presence of outliers. 

In [56]:
from sklearn.preprocessing import StandardScaler
data = [[0, 0], [0, 0], [1, 1], [1, 1]]
scaler = StandardScaler()
scaler.fit(data)

StandardScaler()

In [57]:
scaler.transform(data)

array([[-1., -1.],
       [-1., -1.],
       [ 1.,  1.],
       [ 1.,  1.]])

# Make Column Selector

Create a callable to select columns to be used with ColumnTransformer.

make_column_selector can select columns based on datatype or the columns name with a regex. When using multiple selection criteria, all criteria must match for a column to be selected.

In [59]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.compose import make_column_selector
import numpy as np
import pandas as pd  

X = pd.DataFrame({'city': ['London', 'London', 'Paris', 'Sallisaw'],
                  'rating': [5, 3, 4, 5]})  
ct = make_column_transformer(
      (StandardScaler(),
       make_column_selector(dtype_include=np.number)),  # rating
      (OneHotEncoder(),
       make_column_selector(dtype_include=object)))  # city
ct.fit_transform(X)  

array([[ 0.90453403,  1.        ,  0.        ,  0.        ],
       [-1.50755672,  1.        ,  0.        ,  0.        ],
       [-0.30151134,  0.        ,  1.        ,  0.        ],
       [ 0.90453403,  0.        ,  0.        ,  1.        ]])

## Pipeline

Pipeline of transforms with a final estimator.

Sequentially apply a list of transforms and a final estimator. Intermediate steps of the pipeline must be ‘transforms’, that is, they must implement fit and transform methods. The final estimator only needs to implement fit. The transformers in the pipeline can be cached using memory argument.

In [60]:
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline



X, y = make_classification(random_state=0)
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    random_state=0)

In [61]:
pipe = Pipeline([('scaler', StandardScaler()), ('svc', SVC())])
# The pipeline can be used as any other estimator
# and avoids leaking the test set into the train set

pipe.fit(X_train, y_train).score(X_test, y_test)

0.88

In [62]:
# An estimator's parameter can be set using '__' syntax
pipe.set_params(svc__C=10).fit(X_train, y_train).score(X_test, y_test)

0.76

# Melt, Pivot, Unpivot

## Pandas Pivot

The pivot() function is used to reshaped a given DataFrame organized by given index / column values. This function does not support data aggregation, multiple values will result in a MultiIndex in the columns.

Syntax:

DataFrame.pivot(self, index=None, columns=None, values=None)

In [63]:
import numpy as np
import pandas as pd

df = pd.DataFrame({'fff': ['one', 'one', 'one', 'two', 'two',
                           'two'],
                   'bbb': ['P', 'Q', 'R', 'P', 'Q', 'R'],
                   'baa': [2, 3, 4, 5, 6, 7],
                   'zzz': ['h', 'i', 'j', 'k', 'l', 'm']})
df

fff bbb  baa zzz
0  one   P    2   h
1  one   Q    3   i
2  one   R    4   j
3  two   P    5   k
4  two   Q    6   l
5  two   R    7   m

![](https://www.w3resource.com/w3r_images/pandas-dataframe-pivot.svg)

In [64]:
df.pivot(index='fff', columns='bbb', values='baa')

bbb  P  Q  R
fff         
one  2  3  4
two  5  6  7

![](https://www.w3resource.com/w3r_images/pandas-dataframe-pivot-1.svg)

In [68]:
df.pivot(index='fff', columns='bbb', values=['baa', 'zzz'])

baa       zzz      
bbb   P  Q  R   P  Q  R
fff                    
one   2  3  4   h  i  j
two   5  6  7   k  l  m

![](https://www.w3resource.com/w3r_images/pandas-dataframe-pivot-2.svg)

## Melt() function

The melt() function is used to unpivot a given DataFrame from wide format to long format, optionally leaving identifier variables set.

In [69]:
import numpy as np
import pandas as pd

In [70]:
df = pd.DataFrame({'P': {0: 'p', 1: 'q', 2: 'r'},
                   'Q': {0: 1, 1: 3, 2: 5},
                   'R': {0: 2, 1: 4, 2: 6}})
df

P  Q  R
0  p  1  2
1  q  3  4
2  r  5  6

In [72]:
df.melt(id_vars=['P'], value_vars=['Q'])

P variable  value
0  p        Q      1
1  q        Q      3
2  r        Q      5

In [73]:
df.melt(id_vars=['P'], value_vars=['Q', 'R'])

P variable  value
0  p        Q      1
1  q        Q      3
2  r        Q      5
3  p        R      2
4  q        R      4
5  r        R      6

## explode()

The explode() function is used to transform each element of a list-like to a row, replicating the index values.

In [74]:
import numpy as np
import pandas as pd

df = pd.DataFrame({'P': [[2, 3, 4], 'fff', [], [4, 5]], 'Q': 2})
df

P  Q
0  [2, 3, 4]  2
1        fff  2
2         []  2
3     [4, 5]  2

![](https://www.w3resource.com/w3r_images/pandas-dataframe-explode.png)

In [75]:
df = pd.DataFrame({'P': [[2, 3, 4], 'fff', [], [4, 5]], 'Q': 2})
df.explode('P')

P  Q
0    2  2
0    3  2
0    4  2
1  fff  2
2  NaN  2
3    4  2
3    5  2

![](https://www.w3resource.com/w3r_images/pandas-dataframe-explode-1.png)

## pandas.DataFrame.query


Query the columns of a DataFrame with a boolean expression.

In [126]:
df = pd.DataFrame({'A': range(1, 6),

                   'B': range(10, 0, -2),

                   'C C': range(10, 5, -1)})
df

A   B  C C
0  1  10   10
1  2   8    9
2  3   6    8
3  4   4    7
4  5   2    6

In [129]:
df.query('A > B')

A  B  C C
4  5  2    6

In [127]:
df[df.A > df.B]

A  B  C C
4  5  2    6

In [128]:
df.query('B == `C C`')

A   B  C C
0  1  10   10

### More example

In [131]:
# Create DataFrame
import pandas as pd
import numpy as np
technologies= {
    'Courses':["Spark","PySpark","Hadoop","Python","Pandas"],
    'Fee' :[22000,25000,23000,24000,26000],
    'Duration':['30days','50days','30days', None,np.nan],
    'Discount':[1000,2300,1000,1200,2500]
          }
df = pd.DataFrame(technologies)
df

Courses    Fee Duration  Discount
0    Spark  22000   30days      1000
1  PySpark  25000   50days      2300
2   Hadoop  23000   30days      1000
3   Python  24000     None      1200
4   Pandas  26000      NaN      2500

In [132]:
df.query("Courses == 'Spark'")

Courses    Fee Duration  Discount
0   Spark  22000   30days      1000

In [134]:
df.query("Courses in ('Spark','PySpark')")

Courses    Fee Duration  Discount
0    Spark  22000   30days      1000
1  PySpark  25000   50days      2300

# Table visulize
---

## Formatting the Display

In [2]:
%pip install Jinja2

  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
  Obtaining dependency information for MarkupSafe>=2.0 from https://files.pythonhosted.org/packages/be/bb/08b85bc194034efbf572e70c3951549c8eca0ada25363afc154386b5390a/MarkupSafe-2.1.3-cp311-cp311-win_amd64.whl.metadata
Using cached MarkupSafe-2.1.3-cp311-cp311-win_amd64.whl (17 kB)
Note: you may need to restart the kernel to use updated packages.


In [1]:
import pandas as pd
import numpy as np
import matplotlib as mpl

df = pd.DataFrame({
    "strings": ["Adam", "Mike"],
    "ints": [1, 3],
    "floats": [1.123, 1000.23]
})
df.style \
  .format(precision=3, thousands=".", decimal=",") \
  .format_index(str.upper, axis=1) \
  .relabel_index(["row 1", "row 2"], axis=0)

In [2]:
weather_df = pd.DataFrame(np.random.rand(10,2)*5,
                          index=pd.date_range(start="2021-01-01", periods=10),
                          columns=["Tokyo", "Beijing"])

def rain_condition(v):
    if v < 1.75:
        return "Dry"
    elif v < 2.75:
        return "Rain"
    return "Heavy Rain"

def make_pretty(styler):
    styler.set_caption("Weather Conditions")
    styler.format(rain_condition)
    styler.format_index(lambda v: v.strftime("%A"))
    styler.background_gradient(axis=None, vmin=1, vmax=5, cmap="YlGnBu")
    return styler

weather_df

Tokyo   Beijing
2021-01-01  4.241692  4.606167
2021-01-02  2.102589  2.529845
2021-01-03  4.653678  1.734745
2021-01-04  4.174940  4.837378
2021-01-05  0.681953  1.874010
2021-01-06  0.505734  3.393434
2021-01-07  0.080450  0.807169
2021-01-08  0.494767  4.920938
2021-01-09  3.969437  1.428277
2021-01-10  0.828718  4.608179

In [3]:
weather_df.loc["2021-01-04":"2021-01-08"].style.pipe(make_pretty)

In [5]:
df = pd.DataFrame(np.random.randn(5, 5))
df.style \
  .hide(subset=[0, 2, 4], axis=0) \
  .hide(subset=[0, 2, 4], axis=1)

In [6]:
show = [0, 2, 4]
df.style \
  .hide([row for row in df.index if row not in show], axis=0) \
  .hide([col for col in df.columns if col not in show], axis=1)

In [7]:
summary_styler = df.agg(["sum", "mean"]).style \
                   .format(precision=3) \
                   .relabel_index(["Sum", "Average"])
df.style.format(precision=1).concat(summary_styler)

## Styler Object and HTML

In [8]:
df = pd.DataFrame([[38.0, 2.0, 18.0, 22.0, 21, np.nan],[19, 439, 6, 452, 226,232]],
                  index=pd.Index(['Tumour (Positive)', 'Non-Tumour (Negative)'], name='Actual Label:'),
                  columns=pd.MultiIndex.from_product([['Decision Tree', 'Regression', 'Random'],['Tumour', 'Non-Tumour']], names=['Model:', 'Predicted:']))
df.style

In [10]:
s = df.style.format('{:.0f}').hide([('Random', 'Tumour'), ('Random', 'Non-Tumour')], axis="columns")
s

In [11]:
cell_hover = {  # for row hover use <tr> instead of <td>
    'selector': 'td:hover',
    'props': [('background-color', '#ffffb3')]
}
index_names = {
    'selector': '.index_name',
    'props': 'font-style: italic; color: darkgrey; font-weight:normal;'
}
headers = {
    'selector': 'th:not(.index_name)',
    'props': 'background-color: #000066; color: white;'
}
s.set_table_styles([cell_hover, index_names, headers])

In [12]:
s.set_table_styles([
    {'selector': 'th.col_heading', 'props': 'text-align: center;'},
    {'selector': 'th.col_heading.level0', 'props': 'font-size: 1.5em;'},
    {'selector': 'td', 'props': 'text-align: center; font-weight: bold;'},
], overwrite=False)

In [13]:
s.set_table_styles({
    ('Regression', 'Tumour'): [{'selector': 'th', 'props': 'border-left: 1px solid white'},
                               {'selector': 'td', 'props': 'border-left: 1px solid #000066'}]
}, overwrite=False, axis=0)

In [15]:
s.set_table_styles([  # create internal CSS classes
    {'selector': '.true', 'props': 'background-color: #e6ffe6;'},
    {'selector': '.false', 'props': 'background-color: #ffe6e6;'},
], overwrite=False)
cell_color = pd.DataFrame([['true ', 'false ', 'true ', 'false '],
                           ['false ', 'true ', 'false ', 'true ']],
                          index=df.index,
                          columns=df.columns[:4])
s.set_td_classes(cell_color)

## Styler Functions

In [21]:
np.random.seed(0)
df2 = pd.DataFrame(np.random.randn(10,4), columns=['A','B','C','D'])
df2.style

In [24]:
def style_negative(v, props=''):
    return props if v < 0 else None
s2 = df2.style.applymap(style_negative, props='color:red;')\
              .applymap(lambda v: 'opacity: 20%;' if (v < 0.3) and (v > -0.3) else None)
s2

In [25]:
def highlight_max(s, props=''):
    return np.where(s == np.nanmax(s.values), props, '')


s2.apply(highlight_max, props='color:white;background-color:darkblue', axis=0)

In [26]:
s2.apply(highlight_max, props='color:white;background-color:pink;', axis=1)\
  .apply(highlight_max, props='color:white;background-color:purple', axis=None)

## Tooltips and Captions

In [37]:
s.set_caption("Confusion matrix for multiple cancer prediction models.")\
 .set_table_styles([{
     'selector': 'caption',
     'props': 'caption-side: bottom; font-size:1.25em;'
 }], overwrite=False)

In [38]:
tt = pd.DataFrame([['This model has a very strong true positive rate',
                    "This model's total number of false negatives is too high"]],
                  index=['Tumour (Positive)'], columns=df.columns[[0,3]])
s.set_tooltips(tt, props='visibility: hidden; position: absolute; z-index: 1; border: 1px solid #000066;'
                         'background-color: white; color: #000066; font-size: 0.8em;'
                         'transform: translate(0px, -24px); padding: 0.6em; border-radius: 0.5em;')

## Finer Control with Slicing

In [41]:
df3 = pd.DataFrame(np.random.randn(4,4),
                   pd.MultiIndex.from_product([['A', 'B'], ['r1', 'r2']]),
                   columns=['c1','c2','c3','c4'])
df3

c1        c2        c3        c4
A r1 -1.048553 -1.420018 -1.706270  1.950775
  r2 -0.509652 -0.438074 -1.252795  0.777490
B r1 -1.613898 -0.212740 -0.895467  0.386902
  r2 -0.510805 -1.180632 -0.028182  0.428332

In [42]:
slice_ = ['c3', 'c4']
df3.style.apply(highlight_max, props='color:red;', axis=0, subset=slice_)\
         .set_properties(**{'background-color': '#ffffb3'}, subset=slice_)

In [43]:
idx = pd.IndexSlice
slice_ = idx[idx[:,'r1'], idx['c2':'c4']]
df3.style.apply(highlight_max, props='color:red;', axis=0, subset=slice_)\
         .set_properties(**{'background-color': '#ffffb3'}, subset=slice_)

## Builtin Styles

In [44]:
df2.iloc[0,2] = np.nan
df2.iloc[4,3] = np.nan
df2.loc[:4].style.highlight_null(color='yellow')

In [45]:
df2.loc[:4].style.highlight_max(axis=1, props='color:white; font-weight:bold; background-color:darkblue;')

In [46]:
left = pd.Series([1.0, 0.0, 1.0], index=["A", "B", "D"])
df2.loc[:4].style.highlight_between(left=left, right=1.5, axis=1, props='color:white; background-color:purple;')

In [47]:
df2.loc[:4].style.highlight_quantile(q_left=0.85, axis=None, color='yellow')

In [48]:
import seaborn as sns
cm = sns.light_palette("green", as_cmap=True)

df2.style.background_gradient(cmap=cm)

In [49]:
df2.style.text_gradient(cmap=cm)

In [50]:
df2.loc[:4].style.set_properties(**{'background-color': 'black',
                           'color': 'lawngreen',
                           'border-color': 'white'})

In [51]:
df2.style.bar(subset=['A', 'B'], color='#d65f5f')

In [52]:
df2.style.format('{:.3f}', na_rep="")\
         .bar(align=0, vmin=-2.5, vmax=2.5, cmap="bwr", height=50,
              width=60, props="width: 120px; border-right: 1px solid black;")\
         .text_gradient(cmap="bwr", vmin=-2.5, vmax=2.5)

In [54]:
def magnify():
    return [dict(selector="th",
                 props=[("font-size", "4pt")]),
            dict(selector="td",
                 props=[('padding', "0em 0em")]),
            dict(selector="th:hover",
                 props=[("font-size", "12pt")]),
            dict(selector="tr:hover td:hover",
                 props=[('max-width', '200px'),
                        ('font-size', '12pt')])
]

In [55]:
np.random.seed(25)
cmap = cmap=sns.diverging_palette(5, 250, as_cmap=True)
bigdf = pd.DataFrame(np.random.randn(20, 25)).cumsum()

bigdf.style.background_gradient(cmap, axis=1)\
    .set_properties(**{'max-width': '80px', 'font-size': '1pt'})\
    .set_caption("Hover to magnify")\
    .format(precision=2)\
    .set_table_styles(magnify())

# Time Series

In [56]:
import datetime

dti = pd.to_datetime(
        ["1/1/2018", np.datetime64("2018-01-01"), datetime.datetime(2018, 1, 1)])

dti

DatetimeIndex(['2018-01-01', '2018-01-01', '2018-01-01'], dtype='datetime64[ns]', freq=None)

In [57]:
dti = pd.date_range("2018-01-01", periods=3, freq="H")

dti

DatetimeIndex(['2018-01-01 00:00:00', '2018-01-01 01:00:00',
               '2018-01-01 02:00:00'],
              dtype='datetime64[ns]', freq='H')

In [58]:
dti = dti.tz_localize("UTC")

dti

DatetimeIndex(['2018-01-01 00:00:00+00:00', '2018-01-01 01:00:00+00:00',
               '2018-01-01 02:00:00+00:00'],
              dtype='datetime64[ns, UTC]', freq='H')

In [59]:
dti.tz_convert("US/Pacific")

DatetimeIndex(['2017-12-31 16:00:00-08:00', '2017-12-31 17:00:00-08:00',
               '2017-12-31 18:00:00-08:00'],
              dtype='datetime64[ns, US/Pacific]', freq='H')

In [60]:
idx = pd.date_range("2018-01-01", periods=5, freq="H")

ts = pd.Series(range(len(idx)), index=idx)

ts

2018-01-01 00:00:00    0
2018-01-01 01:00:00    1
2018-01-01 02:00:00    2
2018-01-01 03:00:00    3
2018-01-01 04:00:00    4
Freq: H, dtype: int64

In [61]:
ts.resample("2H").mean()

2018-01-01 00:00:00    0.5
2018-01-01 02:00:00    2.5
2018-01-01 04:00:00    4.0
Freq: 2H, dtype: float64

In [63]:
friday = pd.Timestamp("2018-01-05")

friday.day_name()

'Friday'

In [64]:
saturday = friday + pd.Timedelta("1 day")

saturday.day_name()

'Saturday'

In [65]:
monday = friday + pd.offsets.BDay()

monday.day_name()

'Monday'

In [80]:
ts = pd.Series(pd.date_range("2023", freq="M", periods=3))
ts

0   2023-01-31
1   2023-02-28
2   2023-03-31
dtype: datetime64[ns]

In [69]:
pd.Series(pd.date_range("1/1/2011", freq="M", periods=3))

0   2011-01-31
1   2011-02-28
2   2011-03-31
dtype: datetime64[ns]

## NaT

pandas represents null date times, time deltas, and time spans as NaT which is useful for representing missing or null date like values and behaves similar as np.nan does for float data.

In [70]:
pd.Timestamp(pd.NaT)

NaT

In [71]:
idx = pd.date_range(start="2019-12-29", freq="D", periods=4)

idx.isocalendar()

year  week  day
2019-12-29  2019    52    7
2019-12-30  2020     1    1
2019-12-31  2020     1    2
2020-01-01  2020     1    3

In [81]:
ts.shift(1)

0          NaT
1   2023-01-31
2   2023-02-28
dtype: datetime64[ns]

# Plotly

### basic plot in plotly

In [84]:
import plotly.express as px

fig = px.line(x=["a","b","c"], y=[1,3,2], title="sample figure")
fig.show()

## scater

In [85]:
import plotly.express as px
fig = px.scatter(x=[0, 1, 2, 3, 4], y=[0, 1, 4, 9, 16])
fig.show()

In [86]:
df = px.data.iris() # iris is a pandas DataFrame
fig = px.scatter(df, x="sepal_width", y="sepal_length")
fig.show()

In [87]:
df = px.data.iris()
fig = px.scatter(df, x="sepal_width", y="sepal_length", color="species",
                 size='petal_length', hover_data=['petal_width'])
fig.show()

In [88]:
df = px.data.iris()
fig = px.scatter(df, x="sepal_width", y="sepal_length", color='petal_length')
fig.show()

In [89]:
df = px.data.iris()
fig = px.scatter(df, x="sepal_length", y="sepal_width", marginal_x="histogram", marginal_y="rug")
fig.show()

In [90]:
df = px.data.tips()
fig = px.scatter(df, x="total_bill", y="tip", color="smoker", facet_col="sex", facet_row="time")
fig.show()

In [ ]:
%pip install statsmodels

In [93]:
df = px.data.tips()
fig = px.scatter(df, x="total_bill", y="tip", trendline="ols")
fig.show()

### Line plots with Plotly Express

In [94]:
import numpy as np

t = np.linspace(0, 2*np.pi, 100)

fig = px.line(x=t, y=np.cos(t), labels={'x':'t', 'y':'cos(t)'})
fig.show()

In [95]:
df = px.data.gapminder().query("continent == 'Oceania'")
fig = px.line(df, x='year', y='lifeExp', color='country')
fig.show()

In [96]:
df = px.data.gapminder().query("continent == 'Oceania'")
fig = px.line(df, x='year', y='lifeExp', color='country', markers=True)
fig.show()

## Line plots on Date axes

Line plots can be made on using any type of cartesian axis, including linear, logarithmic, categorical or date axes. Line plots on date axes are often called time-series charts.

In [97]:
df = px.data.stocks()
fig = px.line(df, x='date', y="GOOG")
fig.show()

In [98]:
df = px.data.gapminder().query("country in ['Canada', 'Botswana']")

fig = px.line(df, x="lifeExp", y="gdpPercap", color="country", text="year")
fig.update_traces(textposition="bottom right")
fig.show()

### Bar chart with Plotly Express

In [99]:
data_canada = px.data.gapminder().query("country == 'Canada'")
fig = px.bar(data_canada, x='year', y='pop')
fig.show()

In [100]:
long_df = px.data.medals_long()

fig = px.bar(long_df, x="nation", y="count", color="medal", title="Long-Form Input")
fig.show()

In [101]:
df = px.data.gapminder().query("country == 'Canada'")
fig = px.bar(df, x='year', y='pop',
             hover_data=['lifeExp', 'gdpPercap'], color='lifeExp',
             labels={'pop':'population of Canada'}, height=400)
fig.show()

In [102]:
df = px.data.gapminder().query("continent == 'Oceania'")
fig = px.bar(df, x='year', y='pop',
             hover_data=['lifeExp', 'gdpPercap'], color='country',
             labels={'pop':'population of Canada'}, height=400)
fig.show()

In [104]:
df = px.data.medals_long()
fig = px.bar(df, x="medal", y="count", color="nation", text_auto=True)
fig.show()

In [105]:
df = px.data.gapminder().query("continent == 'Europe' and year == 2007 and pop > 2.e6")
fig = px.bar(df, y='pop', x='country', text_auto='.2s',
            title="Default: various text sizes, positions and angles")
fig.show()

In [106]:
df = px.data.medals_long()

fig = px.bar(df, x="medal", y="count", color="nation",
             pattern_shape="nation", pattern_shape_sequence=[".", "x", "+"])
fig.show()

In [107]:
import plotly.graph_objects as go
animals=['giraffes', 'orangutans', 'monkeys']

fig = go.Figure(data=[
    go.Bar(name='SF Zoo', x=animals, y=[20, 14, 23]),
    go.Bar(name='LA Zoo', x=animals, y=[12, 18, 29])
])
# Change the bar mode
fig.update_layout(barmode='group')
fig.show()

### Pie chart with plotly express

In [108]:
import plotly.express as px
df = px.data.gapminder().query("year == 2007").query("continent == 'Europe'")
df.loc[df['pop'] < 2.e6, 'country'] = 'Other countries' # Represent only large countries
fig = px.pie(df, values='pop', names='country', title='Population of European continent')
fig.show()

In [109]:
df = px.data.tips()
fig = px.pie(df, values='tip', names='day', color_discrete_sequence=px.colors.sequential.RdBu)
fig.show()

In [110]:
df = px.data.tips()
fig = px.pie(df, values='tip', names='day', color='day',
             color_discrete_map={'Thur':'lightcyan',
                                 'Fri':'cyan',
                                 'Sat':'royalblue',
                                 'Sun':'darkblue'})
fig.show()

In [111]:
df = px.data.gapminder().query("year == 2007").query("continent == 'Americas'")
fig = px.pie(df, values='pop', names='country',
             title='Population of American continent',
             hover_data=['lifeExp'], labels={'lifeExp':'life expectancy'})
fig.update_traces(textposition='inside', textinfo='percent+label')
fig.show()

### Donut Chart

In [112]:
import plotly.graph_objects as go

labels = ['Oxygen','Hydrogen','Carbon_Dioxide','Nitrogen']
values = [4500, 2500, 1053, 500]

# Use `hole` to create a donut-like pie chart
fig = go.Figure(data=[go.Pie(labels=labels, values=values, hole=.3)])
fig.show()

In [113]:
import plotly.graph_objects as go

labels = ['Oxygen','Hydrogen','Carbon_Dioxide','Nitrogen']
values = [4500, 2500, 1053, 500]

# pull is given as a fraction of the pie radius
fig = go.Figure(data=[go.Pie(labels=labels, values=values, pull=[0, 0, 0.2, 0])])
fig.show()

### Sunburst charts

In [114]:
import plotly.graph_objects as go

fig =go.Figure(go.Sunburst(
    labels=["Eve", "Cain", "Seth", "Enos", "Noam", "Abel", "Awan", "Enoch", "Azura"],
    parents=["", "Eve", "Eve", "Seth", "Seth", "Eve", "Eve", "Awan", "Eve" ],
    values=[10, 14, 12, 10, 2, 6, 6, 4, 4],
))
fig.update_layout(margin = dict(t=0, l=0, r=0, b=0))

fig.show()

### Bubble chart with plotly.express

In [115]:
df = px.data.gapminder()

fig = px.scatter(df.query("year==2007"), x="gdpPercap", y="lifeExp",
	         size="pop", color="continent",
                 hover_name="country", log_x=True, size_max=60)
fig.show()

### Box Plot with plotly.express

In [116]:
df = px.data.tips()
fig = px.box(df, y="total_bill")
fig.show()

In [117]:
df = px.data.tips()
fig = px.box(df, x="time", y="total_bill")
fig.show()

In [118]:
df = px.data.tips()
fig = px.box(df, x="time", y="total_bill", points="all")
fig.show()

In [119]:
df = px.data.tips()

fig = px.box(df, x="day", y="total_bill", color="smoker")
fig.update_traces(quartilemethod="exclusive") # or "inclusive", or "linear" by default
fig.show()

### Histograms with Plotly Express

In [120]:
df = px.data.tips()
fig = px.histogram(df, x="total_bill")
fig.show()

In [121]:
df = px.data.tips()
fig = px.histogram(df, x="total_bill", color="sex")
fig.show()

### Basic Distplot

In [122]:
import plotly.figure_factory as ff
import numpy as np
np.random.seed(1)

x = np.random.randn(1000)
hist_data = [x]
group_labels = ['distplot'] # name of the dataset

fig = ff.create_distplot(hist_data, group_labels)
fig.show()

### Plot Multiple Datasets

In [123]:
import plotly.figure_factory as ff
import numpy as np

# Add histogram data
x1 = np.random.randn(200) - 2
x2 = np.random.randn(200)
x3 = np.random.randn(200) + 2
x4 = np.random.randn(200) + 4

# Group data together
hist_data = [x1, x2, x3, x4]

group_labels = ['Group 1', 'Group 2', 'Group 3', 'Group 4']

# Create distplot with custom bin_size
fig = ff.create_distplot(hist_data, group_labels, bin_size=.2)
fig.show()

### Plot Only Curve and Rug

In [124]:

x1 = np.random.randn(200) - 1
x2 = np.random.randn(200)
x3 = np.random.randn(200) + 1

hist_data = [x1, x2, x3]

group_labels = ['Group 1', 'Group 2', 'Group 3']
colors = ['#333F44', '#37AA9C', '#94F3E4']

# Create distplot with curve_type set to 'normal'
fig = ff.create_distplot(hist_data, group_labels, show_hist=False, colors=colors)

# Add title
fig.update_layout(title_text='Curve and Rug Plot')
fig.show()

### For More Information:
Check this website:

https://plotly.com/python/

## Cross tab

![](https://pbpython.com/images/crosstab_cheatsheet_header.png)

In [16]:
from seaborn import load_dataset
df = load_dataset("tips")
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [17]:
pd.crosstab(df['time'], df['day'])

day     Thur  Fri  Sat  Sun
time                       
Lunch     61    7    0    0
Dinner     1   12   87   76

In [18]:
car_names = ['Suzuki','Honda','Toyota','Jeep','Tata']
fuel_type = ['diesel','petrol','diesel','petrol','diesel']
price = [10, 18, 27, 35, 15]

pd.crosstab(index=[car_names], columns=[fuel_type])

col_0   diesel  petrol
row_0                 
Honda        0       1
Jeep         0       1
Suzuki       1       0
Tata         1       0
Toyota       1       0

In [20]:
df = pd.read_excel('https://github.com/datagy/mediumdata/raw/master/sample_pivot.xlsx', parse_dates=['Date'])
df

Date Region                 Type  Units  Sales
0   2020-07-11   East  Children's Clothing   18.0    306
1   2020-09-23  North  Children's Clothing   14.0    448
2   2020-04-02  South     Women's Clothing   17.0    425
3   2020-02-28   East  Children's Clothing   26.0    832
4   2020-03-19   West     Women's Clothing    3.0     33
..         ...    ...                  ...    ...    ...
995 2020-02-11   East  Children's Clothing   35.0    735
996 2020-12-25  North       Men's Clothing    NaN   1155
997 2020-08-31  South       Men's Clothing   13.0    208
998 2020-08-23  South     Women's Clothing   17.0    493
999 2020-08-17  North     Women's Clothing   25.0    300

[1000 rows x 5 columns]

In [21]:
pd.crosstab(df.Region, df.Type)

Type    Children's Clothing  Men's Clothing  Women's Clothing
Region                                                       
East                    113             122               176
North                    85              89               142
South                    45              39                53
West                     42              41                53

In [22]:
pd.crosstab(index = df.Region, columns = df.Type, values = df.Sales, aggfunc = 'mean')

Type    Children's Clothing  Men's Clothing  Women's Clothing
Region                                                       
East             405.743363      423.647541        399.028409
North            438.894118      449.157303        432.528169
South            412.666667      475.435897        418.924528
West             480.523810      465.292683        419.188679

## Sample

Return a random sample of items from an axis of object.

In [2]:
import pandas as pd

df = pd.DataFrame({'num_legs': [2, 4, 8, 0],
                   'num_wings': [2, 0, 0, 0],
                   'num_specimen_seen': [10, 2, 1, 8]},
                  index=['falcon', 'dog', 'spider', 'fish'])
df

num_legs  num_wings  num_specimen_seen
falcon         2          2                 10
dog            4          0                  2
spider         8          0                  1
fish           0          0                  8

In [6]:
df.sample(n=2, random_state=1)

num_legs  num_wings  num_specimen_seen
fish           0          0                  8
spider         8          0                  1

In [7]:
df.sample(frac=0.5, replace=True, random_state=1)

num_legs  num_wings  num_specimen_seen
dog          4          0                  2
fish         0          0                  8

## pivot_table

![](https://builtin.com/sites/www.builtin.com/files/styles/ckeditor_optimize/public/inline-images/1_pandas-pivot-table.jpeg)

In [8]:
import pandas as pd
import numpy as np
from sklearn.datasets import fetch_openml

X,y = fetch_openml("autos", version=1, as_frame=True, return_X_y=True)
data = X
data['target'] = y

c:\Users\og122665\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\datasets\_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


In [10]:
data

normalized-losses         make fuel-type aspiration num-of-doors  \
0                None  alfa-romero       gas        std          two   
1                 NaN  alfa-romero       gas        std          two   
2                 NaN  alfa-romero       gas        std          two   
3               164.0         audi       gas        std         four   
4               164.0         audi       gas        std         four   
..                ...          ...       ...        ...          ...   
200              95.0        volvo       gas        std         four   
201              95.0        volvo       gas      turbo         four   
202              95.0        volvo       gas        std         four   
203              95.0        volvo    diesel      turbo         four   
204              95.0        volvo       gas      turbo         four   

      body-style drive-wheels engine-location  wheel-base  length  ...  \
0    convertible          rwd           front        88.6   168.8  ...   
1    convertible          rwd           front        88.6   168.8  ...   
2      hatchback          rwd           front        94.5   171.2  ...   
3          sedan          fwd           front        99.8   176.6  ...   
4          sedan          4wd           front        99.4   176.6  ...   
..           ...          ...             ...         ...     ...  ...   
200        sedan          rwd           front       109.1   188.8  ...   
201        sedan          rwd           front       109.1   188.8  ...   
202        sedan          rwd           front       109.1   188.8  ...   
203        sedan          rwd           front       109.1   188.8  ...   
204        sedan          rwd           front       109.1   188.8  ...   

     fuel-system  bore  stroke compression-ratio horsepower  peak-rpm  \
0           mpfi  3.47    2.68               9.0      111.0    5000.0   
1           mpfi  3.47    2.68               9.0      111.0    5000.0   
2           mpfi  2.68    3.47               9.0      154.0    5000.0   
3           mpfi  3.19    3.40              10.0      102.0    5500.0   
4           mpfi  3.19    3.40               8.0      115.0    5500.0   
..           ...   ...     ...               ...        ...       ...   
200         mpfi  3.78    3.15               9.5      114.0    5400.0   
201         mpfi  3.78    3.15               8.7      160.0    5300.0   
202         mpfi  3.58    2.87               8.8      134.0    5500.0   
203          idi  3.01    3.40              23.0      106.0    4800.0   
204         mpfi  3.78    3.15               9.5      114.0    5400.0   

    city-mpg  highway-mpg    price  target  
0       21.0         27.0  13495.0       3  
1       21.0         27.0  16500.0       3  
2       19.0         26.0  16500.0       1  
3       24.0         30.0  13950.0       2  
4       18.0         22.0  17450.0       2  
..       ...          ...      ...     ...  
200     23.0         28.0  16845.0      -1  
201     19.0         25.0  19045.0      -1  
202     18.0         23.0  21485.0      -1  
203     26.0         27.0  22470.0      -1  
204     19.0         25.0  22625.0      -1  

[205 rows x 26 columns]

In [9]:
pivot = np.round(pd.pivot_table(data, values='price', 
                                index='num-of-doors', 
                                columns='fuel-type', 
                                aggfunc=np.mean),2)
pivot

fuel-type       diesel       gas
num-of-doors                    
four          16432.38  13092.81
two           14350.00  12762.76

In [11]:
pivot = np.round(pd.pivot_table(data, values='price', 
                                index=['num-of-doors', 'body-style'], 
                                columns=['fuel-type', 'fuel-system'], 
                                aggfunc=np.mean,
                                fill_value=0),2)
pivot

fuel-type                   diesel      gas                                   \
fuel-system                    idi     1bbl     2bbl   4bbl    mfi      mpfi   
num-of-doors body-style                                                        
four         hatchback     7788.00     0.00  7813.71      0      0  10618.00   
             sedan        16328.92  8811.67  7711.19      0      0  18425.68   
             wagon        19727.67  7295.00  8028.89      0      0  14213.42   
two          convertible      0.00     0.00     0.00      0      0  21890.50   
             hardtop      28176.00     0.00  8249.00      0      0  23540.50   
             hatchback        0.00  7054.43  6701.67  12145  12964  14581.50   
             sedan         7437.00     0.00  7570.00      0      0  21034.00   

fuel-type                                  
fuel-system                   spdi   spfi  
num-of-doors body-style                    
four         hatchback        0.00      0  
             sedan         9279.00      0  
             wagon            0.00      0  
two          convertible      0.00      0  
             hardtop          0.00      0  
             hatchback    11479.43  11048  
             sedan            0.00      0

In [12]:
np.round(pd.pivot_table(data, values='price', 
                                index=['body-style'], 
                                columns=['num-of-doors'], 
                                aggfunc=[np.mean, np.median],
                                fill_value=0),2)

mean           median         
num-of-doors      four       two   four      two
body-style                                      
convertible       0.00  21890.50      0  17084.5
hardtop           0.00  22208.50      0  19687.5
hatchback      8372.00  10230.79   8073   8970.0
sedan         14614.13  14283.00  12555   8678.0
wagon         12371.96      0.00  11694      0.0

## Filter

Subset the dataframe rows or columns according to the specified index labels.

Note that this routine does not filter a dataframe on its contents. The filter is applied to the labels of the index.

In [3]:
import pandas as pd
import numpy as np

df = pd.DataFrame(np.array(([1, 2, 3], [4, 5, 6])),

                  index=['mouse', 'rabbit'],

                  columns=['one', 'two', 'three'])

df

one  two  three
mouse     1    2      3
rabbit    4    5      6

In [4]:
# select columns by name

df.filter(items=['one', 'three'])

one  three
mouse     1      3
rabbit    4      6

In [5]:
# select columns by regular expression

df.filter(regex='e$', axis=1)

one  three
mouse     1      3
rabbit    4      6

In [6]:
# select rows containing 'bbi'

df.filter(like='bbi', axis=0)

one  two  three
rabbit    4    5      6

# For more information and knowledge check links below:

### Prophet:

[https://machinelearningmastery.com/time-series-forecasting-with-prophet-in-python/]()

### Priori:

[https://intellipaat.com/blog/data-science-apriori-algorithm/]()

### Web Scraping:

[https://realpython.com/python-web-scraping-practical-introduction/]()